/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Michele Andrade
 */
public class TelaInicialFrame extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicialFrame
     */
    public TelaInicialFrame() {
        initComponents();
        //insere título na Janela do aplicativo
        super.setTitle("Cartório do Único Ofício de Benevides");
        
        //desabilita botao maximizar da janela
        super.setResizable(false);
        
        //centraliza o janela no meio da tela
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonGerarProcuracao = new javax.swing.JButton();
        jButtonCadastrarProcolo = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelBrasao = new javax.swing.JLabel();
        jButtonCadProc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CARTÓRIO DO ÚNICO OFÍCIO DE BENEVIDES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18))); // NOI18N

        jButtonGerarProcuracao.setText("Gerar Procuração");
        jButtonGerarProcuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarProcuracaoActionPerformed(evt);
            }
        });
        jButtonGerarProcuracao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonGerarProcuracaoKeyPressed(evt);
            }
        });

        jButtonCadastrarProcolo.setText("Cadastrar Protocolo");
        jButtonCadastrarProcolo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonCadastrarProcoloFocusGained(evt);
            }
        });
        jButtonCadastrarProcolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarProcoloActionPerformed(evt);
            }
        });
        jButtonCadastrarProcolo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCadastrarProcoloKeyPressed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jButtonSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonSairKeyPressed(evt);
            }
        });

        jLabelBrasao.setIcon(new javax.swing.ImageIcon("C:\\Arquivos Gerador PDF Java\\Brasao.png")); // NOI18N

        jButtonCadProc.setText("Cadastra Procurações no BD");
        jButtonCadProc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadProcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabelBrasao)
                        .addGap(160, 160, 160))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButtonCadastrarProcolo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCadProc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGerarProcuracao)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSair)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelBrasao, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGerarProcuracao)
                    .addComponent(jButtonCadastrarProcolo)
                    .addComponent(jButtonSair)
                    .addComponent(jButtonCadProc))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonCadastrarProcoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarProcoloActionPerformed
        // TODO add your handling code here:
        ProtocoloFrame obj = new ProtocoloFrame();
        
        obj.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCadastrarProcoloActionPerformed

    private void jButtonGerarProcuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarProcuracaoActionPerformed
        // TODO add your handling code here:
        GeradorProcuracoesFrame obj = new GeradorProcuracoesFrame();
        
        obj.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jButtonGerarProcuracaoActionPerformed

    private void jButtonCadastrarProcoloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonCadastrarProcoloFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonCadastrarProcoloFocusGained
    
    // Se o foco estiver no botao Cadastrar e for apertado Enter, ele chama a tela correspondente
    private void jButtonCadastrarProcoloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCadastrarProcoloKeyPressed
        // TODO add your handling code here:
        getRootPane().setDefaultButton(jButtonCadastrarProcolo);
    }//GEN-LAST:event_jButtonCadastrarProcoloKeyPressed

    private void jButtonGerarProcuracaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonGerarProcuracaoKeyPressed
        // TODO add your handling code here:
        getRootPane().setDefaultButton(jButtonGerarProcuracao);
    }//GEN-LAST:event_jButtonGerarProcuracaoKeyPressed

    private void jButtonSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonSairKeyPressed
        // TODO add your handling code here:
        getRootPane().setDefaultButton(jButtonSair);
    }//GEN-LAST:event_jButtonSairKeyPressed

    private void jButtonCadProcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadProcActionPerformed
        // TODO add your handling code here:
        CadastroProcuracoesFrame obj_proc = new CadastroProcuracoesFrame();
        obj_proc.setVisible(true);
    }//GEN-LAST:event_jButtonCadProcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadProc;
    private javax.swing.JButton jButtonCadastrarProcolo;
    private javax.swing.JButton jButtonGerarProcuracao;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelBrasao;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
