/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;

/**
 *
 * @author Michele Andrade
 */
public class TelaInicial extends javax.swing.JFrame {
    
    public TelaInicial() {
        initComponents();
        this.setExtendedState(TelaInicial.MAXIMIZED_BOTH);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProc = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menProcGerarProcuracao = new javax.swing.JMenuItem();
        menProcCadProcuracao = new javax.swing.JMenuItem();
        menProcCadClientes = new javax.swing.JMenuItem();
        menProcCadUsuarios = new javax.swing.JMenuItem();
        menProt = new javax.swing.JMenu();
        menCivil = new javax.swing.JMenu();
        menImoveis = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menSair = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cartório do Único Ofício de Benevides - Gerenciador de Procurações");

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );

        menuProc.setText("Procuração");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Cadastrar Protocolo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuProc.add(jMenuItem1);

        menProcGerarProcuracao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        menProcGerarProcuracao.setText("Gerar Procuração");
        menProcGerarProcuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menProcGerarProcuracaoActionPerformed(evt);
            }
        });
        menuProc.add(menProcGerarProcuracao);

        menProcCadProcuracao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menProcCadProcuracao.setText("Cadastrar/Consultar Procuração");
        menProcCadProcuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menProcCadProcuracaoActionPerformed(evt);
            }
        });
        menuProc.add(menProcCadProcuracao);

        menProcCadClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menProcCadClientes.setText("Cadastrar/Consultar Clientes");
        menProcCadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menProcCadClientesActionPerformed(evt);
            }
        });
        menuProc.add(menProcCadClientes);

        menProcCadUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        menProcCadUsuarios.setText("Cadastrar/Consultar Usuários");
        menProcCadUsuarios.setEnabled(false);
        menProcCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menProcCadUsuariosActionPerformed(evt);
            }
        });
        menuProc.add(menProcCadUsuarios);

        jMenuBar1.add(menuProc);

        menProt.setText("Protesto");
        jMenuBar1.add(menProt);

        menCivil.setText("Registro Civil");
        jMenuBar1.add(menCivil);

        menImoveis.setText("Registro de Imóveis");
        jMenuBar1.add(menImoveis);

        jMenu5.setText("Sair");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        menSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menSair.setText("Fechar Programa");
        menSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSairActionPerformed(evt);
            }
        });
        jMenu5.add(menSair);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desktop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        //Cria a tela de Protocolo
        ProtocoloFrame protocolo = new ProtocoloFrame();
        //Adiciona a janela no Desktop
        Desktop.add(protocolo);
        
        //abre a janela maximizada (precisa estar dentro de um try...cath)
        try {
	    protocolo.setMaximum(true);
	} catch (Exception e) {
		// TODO: handle exception
	}
        
        //dexia ela visivel
        protocolo.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void menSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menSairActionPerformed

    private void menProcGerarProcuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menProcGerarProcuracaoActionPerformed
         //Cria a tela de Protocolo
        GeradorProcuracoesFrame obj = new GeradorProcuracoesFrame();
        //Adiciona a janela no Desktop
        Desktop.add(obj);
        
        //abre a janela maximizada (precisa estar dentro de um try...cath)
        try {
	    obj.setMaximum(true);
	} catch (Exception e) {
		// TODO: handle exception
	}
        
        //dexia ela visivel
        obj.setVisible(true);
    }//GEN-LAST:event_menProcGerarProcuracaoActionPerformed

    private void menProcCadProcuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menProcCadProcuracaoActionPerformed
        //Cria a tela de Protocolo
        CadastroProcuracoesFrame obj = new CadastroProcuracoesFrame();
        //Adiciona a janela no Desktop
        Desktop.add(obj);
        
        //abre a janela maximizada (precisa estar dentro de um try...cath)
        try {
	    obj.setMaximum(true);
	} catch (Exception e) {
		// TODO: handle exception
	}
        
        //dexia ela visivel
        obj.setVisible(true);
    }//GEN-LAST:event_menProcCadProcuracaoActionPerformed

    private void menProcCadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menProcCadClientesActionPerformed
        //Cria a tela de Protocolo
        CadastroClientesFrame obj = new CadastroClientesFrame();
        //Adiciona a janela no Desktop
        Desktop.add(obj);
        
        //abre a janela maximizada (precisa estar dentro de um try...cath)
        try {
	    obj.setMaximum(true);
	} catch (Exception e) {
		// TODO: handle exception
	}
        
        //dexia ela visivel
        obj.setVisible(true);
    }//GEN-LAST:event_menProcCadClientesActionPerformed

    private void menProcCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menProcCadUsuariosActionPerformed
        //Cria a tela de Protocolo
        CadastroUsuariosFrame obj = new CadastroUsuariosFrame();
        //Adiciona a janela no Desktop
        Desktop.add(obj);
        
//        //abre a janela maximizada (precisa estar dentro de um try...cath)
//        try {
//	    obj.setMaximum(true);
//	} catch (Exception e) {
//		// TODO: handle exception
//	}
//        
        //dexia ela visivel
        obj.setVisible(true);
    }//GEN-LAST:event_menProcCadUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menCivil;
    private javax.swing.JMenu menImoveis;
    private javax.swing.JMenuItem menProcCadClientes;
    private javax.swing.JMenuItem menProcCadProcuracao;
    public static javax.swing.JMenuItem menProcCadUsuarios;
    private javax.swing.JMenuItem menProcGerarProcuracao;
    private javax.swing.JMenu menProt;
    private javax.swing.JMenuItem menSair;
    private javax.swing.JMenu menuProc;
    // End of variables declaration//GEN-END:variables
}
